### ISSUE TITLE
Background image not loading on github pages

### ISSUE THREAD

**Issue by ezioxatul** [ezioxatul/IP-Address-Tracker#1]
### The website works fine when deployed locally, but the background image does not render on github pages

<img width="857" alt="image" src="https://github.com/ezioxatul/IP-Address-Tracker/assets/119116696/e7f7504a-da84-4bc2-90da-ea7bae999efd">

**Comment by MRodriguez-M** [comment]
Hi! I'd like to be able to take a look at this issue.

**Comment by ezioxatul** [comment]
Sure, go ahead

**Comment by itzkavindu** [comment]
um can you allow me the chance to take a closer look at this issue as wel

**Comment by ezioxatul** [comment]
@itzkavindu Thanks for showing your interest on this issue but this issue has been already assigned to someone else,
you can work on other issues i.e. #4 #2

**Comment by ezioxatul** [comment]
It worked, thanks @MRodriguez-M

**Comment by itzkavindu** [comment]
> @itzkavindu Thanks for showing your interest on this issue but this issue has been already assigned to someone else,
> you can work on other issues i.e. #4 #2 

Aaa okyyy
